subjectList = ['Pre-Algebra', 
'Algebra 1', 
'Algebra 1 Honors', 
'Geometry',
'Geometry Honors',
'Algebra 2',
'Algebra 2 Honors',
'Pre-Calculus',
'Pre-Calculus Honors',
'Calculus Honors',
'AP Calculus AB',
'AP Calculus BC',
'Calculus BC Plus',
'AP Statistics',
'Biology',
'Biology Honors',
'AP Biology',
'Chemistry',
'Chemistry Honors',
'AP Chemistry',
'Physics',
'Phsyics Honors',
'AP Physics 1',
'AP Physics C',
'AP Environmental Science',
'Forensics',
'Anatomy',
'Intro to Programming',
'Intro to Web Programming',
'Building Web Apps',
'Applied Algorithmic Design',
'AP Computer Science Principles',
'AP Computer Science A',
'Global Themes',
'Global Themes Honors',
'US History',
'US History Honors',
'AP US History',
'US Government',
'AP US Government and Politics',
'AP US Government and Politics (We the People)',
'AP European History',
'AP World History',
'AP Micro Economics',
'AP Macro Economics',
'English 9',
'English 9 Honors',
'English 10',
'English 10 Honors',
'Myth and Bible',
'Myth and Bible Honors',
'AP English Literature',
'AP English Language'
];